project_id = "zqaeokujqipntjhmbjgi"

[functions.send-liquidation-email]
verify_jwt = false

[functions.process-signature]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.send-user-invitation]
verify_jwt = false

[functions.send-request-notification]
verify_jwt = false

[functions.validate-request-action-token]
verify_jwt = false

[functions.process-request-action]
verify_jwt = false

[functions.send-project-completed-notification]
verify_jwt = false

[functions.extract-invoice-data]
verify_jwt = false

[functions.extract-specialist-invoice-data]
verify_jwt = false
