import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

interface PaymentRegistration {
  payment_date: string;
  amount: number;
  reference?: string;
  payment_method: 'bank_transfer' | 'credit_card' | 'stripe' | 'sdd';
  bank_account?: string;
  notes?: string;
  invoices: Array<{
    id: string;
    allocated_amount: number;
  }>;
}

export const useRegisterPayment = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: PaymentRegistration) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Usuario no autenticado');

      // 1. Create payment record (code is auto-generated by trigger)
      const { data: payment, error: paymentError } = await supabase
        .from('payments')
        .insert({
          payment_date: data.payment_date,
          amount: data.amount,
          reference: data.reference || null,
          payment_method: data.payment_method,
          bank_account: data.bank_account || null,
          notes: data.notes || null,
          created_by: user.id,
          code: '', // Will be auto-generated by trigger
        })
        .select('id, code')
        .single();

      if (paymentError) throw paymentError;

      // 2. Create invoice_payments records
      const invoicePayments = data.invoices.map(inv => ({
        invoice_id: inv.id,
        payment_id: payment.id,
        allocated_amount: inv.allocated_amount,
      }));

      const { error: linkError } = await supabase
        .from('invoice_payments')
        .insert(invoicePayments);

      if (linkError) {
        // Rollback: delete the payment if linking fails
        await supabase.from('payments').delete().eq('id', payment.id);
        throw linkError;
      }

      // 3. Update invoices status to 'paid'
      const invoiceIds = data.invoices.map(inv => inv.id);
      const paymentTimestamp = new Date(data.payment_date).toISOString();

      const { error: updateError } = await supabase
        .from('invoices')
        .update({
          status: 'paid',
          paid_at: paymentTimestamp,
          sent_at: paymentTimestamp, // Ensure constraint is satisfied
        })
        .in('id', invoiceIds);

      if (updateError) {
        // Rollback
        await supabase.from('invoice_payments').delete().eq('payment_id', payment.id);
        await supabase.from('payments').delete().eq('id', payment.id);
        throw updateError;
      }

      return payment;
    },
    onSuccess: (payment) => {
      toast.success(`Cobro ${payment.code} registrado correctamente`);
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      queryClient.invalidateQueries({ queryKey: ['payments'] });
    },
    onError: (error: any) => {
      console.error('Error registering payment:', error);
      toast.error('Error al registrar el cobro: ' + error.message);
    },
  });
};
